google:
  clientKey: "488250433299-cd9m5t86eutqc247m1o2ssvetaotdh2f.apps.googleusercontent.com"
  secret: "IszjZDWShkocSSYZdJ6IcN__"
  callback: "https://project-california.herokuapp.com/auth/google/callback"
  #callback: "http://localhost:3000/auth/google/callback"

mysql:
  username: "b20f0df136ff17"
  password: "89cfdca7"
  host: "us-cdbr-east-02.cleardb.com:3306"
  database: "heroku_8cced30521c6b11"

email:
  username: "projectcalifa@gmail.com"
  password: "t0p0y5#$"
  forgotPasswordUrl: "https://project-california.herokuapp.com/user/forgot-password-reset"
  #forgotPasswordUrl: "http://localhost:3000/user/forgot-password-reset"
