google:
  clientKey: "488250433299-cd9m5t86eutqc247m1o2ssvetaotdh2f.apps.googleusercontent.com"
  secret: "IszjZDWShkocSSYZdJ6IcN__"
  callback: "https://project-california.herokuapp.com/auth/google/callback"

mysql:
  username: "andrerussowsky"
  password: "tatarsz1911"
  host: "db4free.net:3306"
  database: "projectcalifa"
